### ISSUE TITLE
rror: First param to `schema.plugin()` must be a function, got "undefined"

### ISSUE THREAD

**Issue by alexeymo** [Alorel/mongoose-auto-increment-reworked#11]
Hi All,

Looks like I am following the guidance as given in documentation and plugging in MongooseAutoIncrementID into my user schema using schema.plugin. After starting my app I am getting the error: First param to `schema.plugin()` must be a function, got "undefined". Below is the code of my user.js file. Any thoughts would be much appreciated. Thanks in advance

```
var mongoose = require("mongoose");
var passportLocalMongoose = require("passport-local-mongoose");
var MongooseAutoIncrementID = require("mongoose-auto-increment-reworked");

var UserSchemaA = new mongoose.Schema({
    typeB: Boolean,
    userType: String,
    login: String,
    password: String,
    fullName: String,
    email: String,
    companyName: String,
    markets: String,
    value: String,
    technologies: String
});

UserSchemaA.plugin(MongooseAutoIncrementID.plugin, {modelName: "UserA"});
UserSchemaA.plugin(passportLocalMongoose, {usernameField: "login"});

module.exports = mongoose.model("UserA", UserSchemaA);
```

**Comment by Alorel** [comment]
That's not how you apply the plugin. https://github.com/Alorel/mongoose-auto-increment-reworked#basic-usage

**Comment by papaiatis** [comment]
@Alorel 
I believe @alexeymo was right. I don't see any difference in the way he applies the plugin and the way it is shown in the "Basic usage" section. But if I'm not right, please explain why.

What the problem is, that actually `MongooseAutoIncrementID.plugin` is not present. 
It should be `MongooseAutoIncrementID.MongooseAutoIncrementID.plugin` instead.
