### ISSUE TITLE
Continue generate on exist db

### ISSUE THREAD

**Issue by Richtervn** [Alorel/mongoose-auto-increment-reworked#32]
I used mongoose-auto-increment for my old db.
I updated to mongoose-auto-increment-reworked.

Let say I already had documents with _id from 0 to 50.
Now, with mongoose-auto-increment-reworked the _id is reset to 1. How can I make it continue with _id: 51

**Comment by Alorel** [comment]
https://github.com/Alorel/mongoose-auto-increment-reworked#configuration

If you're migrating from the old version you should do **one** of the following:

1. Manually insert IDs in `mongoose-auto-increment-reworked`'s collection in an update script (recommended)
1. Fetch the max ID from your own collection, set it in the config

**Comment by Richtervn** [comment]
```
MongooseAutoIncrementID.setDefaults({
  field: '_id',
  incrementBy: 1,
  nextCount: false,
  resetCount: false,
  unique: true
});
```
Not gonna work. I have to edit idcounters collection myself

**Comment by Alorel** [comment]
Have you actually read the config options available? https://github.com/Alorel/mongoose-auto-increment-reworked/blob/master/src/index.ts#L77

Since you've already generated some false IDs you'll need to clear the collection before you start again with the config option set.

**Comment by Richtervn** [comment]
@Alorel I did, of course. Did you mean the `startAt` option ? This is not what I want. I want it to start at the point where the old counter end

**Comment by Alorel** [comment]
`mongoose-auto-increment-reworked` uses a different schema from the old plugin so it can't reuse the same counters.

The [field names](https://github.com/Alorel/mongoose-auto-increment-reworked/blob/master/src/index.ts#L14) aren't really user-friendly because they weren't made for humans to read, but you could do a data migration manually since they do map 1:1 to the ones used by `mongoose-auto-increment`.

I haven't used that library in a while so I don't remember the actual field names; for the sake of illustrating let's call them `count`, `field` and `model`. You'd need to clear everything you have in the `mongoose-auto-increment-reworked`'s collection and run the following pseudocode:

```javascript
const oldCollection = mongodb.getCollection('old_mongoose_auto_increment');
const newCollection = mongodb.getCollection('new_mongoose_auto_increment_reworked');

oldCollection.find({}).forEach(doc => {
   newCollection.insert({
      c: doc.count,
      f: doc.field,
      m: doc.model
   });
});
```

**Comment by Richtervn** [comment]
@Alorel Yeah, thanks. That's exactly what I want ? A star for you.

**Comment by Alorel** [comment]
Glad to have helped :+1: Sorry if any of the comments sounded aggressive - I only intended to be direct and straight to the point :slightly_smiling_face: 

I'll update the README with some migration docs in the next couple of days in case anyone else has the same problem.
